### ISSUE TITLE
modernize `plot_tax_bar()`

### ISSUE THREAD

**Issue by JCSzamosi** [JCSzamosi/aftersl1p#16]
* stop using `aes_string_()`, which is deprecated. Update to whatever replaced it.
* include a `cutoff` argument in the function itself so that people don't have to re-run `make_tax_df()` to change their cutoff
* provide an option to limit the number of taxa shown in the legend without removing them from the plot

**Comment by bbolker** [comment]
Useful thread about `aes_string()` here: https://fediscience.org/@geospacedman@mastodon.social/110213179086144425

**Comment by JCSzamosi** [comment]
P {margin-top:0;margin-bottom:0;} 



hahaha.




It is actually better than that now. I have pushed the change to the plot_tax_bar branch if you want to look at it.

**Comment by JCSzamosi** [comment]
Fixed by #22
