### ISSUE TITLE
%>% not found

### ISSUE THREAD

**Issue by JCSzamosi** [JCSzamosi/aftersl1p#24]
If the user doesn't have tidyverse loaded, %>% is not found. Need to do something about that.

**Comment by bbolker** [comment]
import it from `magrittr` ?  Or use `|>` if you're OK with depending on R > 4.4.0 (and are not doing anything that the native pipe doesn't support)

**Comment by JCSzamosi** [comment]
Importing it from margrittr is the plan

**Comment by JCSzamosi** [comment]
@bbolker what is the syntax for this? I can import `magrittr`, but then I have to type `magrittr::` before each pipe. How do I import the one function?

**Comment by bbolker** [comment]
```
#' @importFrom magrittr %>%
```
I think.

Again, you might be able to get away with switching to the native pipe `|>`, if (1) you're willing to limit users to R>=4.4 and (2) you're not doing anything fancy with the pipe (see https://stackoverflow.com/questions/67633022/what-are-the-differences-between-rs-native-pipe-and-the-magrittr-pipe )

**Comment by JCSzamosi** [comment]
TY! I think I'd rather not limit people to R >= 4.4, so I'll try this first.

**Comment by JCSzamosi** [comment]
Should work now.
